In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr)


[1 2 3 4 5 6]


In [4]:
# Version of numpy

print(np.__version__)

2.0.0


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
new_arr = np.array((1,2,3,4,5,6,7))

print(new_arr)

[1 2 3 4 5 6 7]


In [10]:
# 0-D Arrays

arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


In [11]:
# 1-D array

arr = np.array([1,2,3,4,5])

print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [13]:
# 2-D array

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
# 3