In [1]:
import tensorflow as tf

In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [27]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [29]:
tensor_string = tf.constant("Hello world")
print(tensor_string)

tf.Tensor(b'Hello world', shape=(), dtype=string)


In [26]:
tensor_one_d = tf.constant([2,0.0,-3,8,90], dtype=tf.float32)
print(tensor_one_d)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [8]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 3  4 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [14]:
tensor_three_d = tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [5,8,0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [11]:
print(tensor_three_d.shape)

(4, 2, 3)


In [17]:
print(tensor_three_d.ndim)

3


In [21]:
tensor_four_d = tf.constant([
    [
        [
            [1,2,0],
            [3,5,-1]
        ],
        [
            [10,2,0],
            [1,0,2]
        ],
        [
            [5,8,0],
            [2,7,0]
        ],
        [
            [2,1,9],
            [4,-3,32]
        ],
    ],
    [
        [
            [13,26,0],
            [3,5,-1]
        ],
        [
            [10,2,0],
            [1,0,2]
        ],
        [
            [5,8,0],
            [2,73,0]
        ],
        [
            [2,1,9],
            [4,-30,32]
        ],
    ]
])

print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[ 13  26   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2  73   0]]

  [[  2   1   9]
   [  4 -30  32]]]], shape=(2, 4, 2, 3), dtype=int32)


In [30]:
import numpy as np

In [32]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [34]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [45]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [47]:
# Preenche todos os elementos com o segundo parametro
fill_tensor = tf.fill(
    [3,4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [48]:
# Preenche com 1s
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [51]:
# Cria um tensor igual formado só de 1s
ones_like_tensor = tf.ones_like(
    fill_tensor,
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [53]:
# Cria um tensor formado só por 0s
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [54]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [55]:
t = tf.constant([[[1,1,1], [2,2,2]], [[3,3,3], [4,4,4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [59]:
tf.size(t, out_type=tf.dtypes.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=12>

In [142]:
random_tensor = tf.random.normal(
    [3,3],
    mean=0.0,
    stddev=10.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 0.10873467 13.493889   -4.3196836 ]
 [ 6.1347203   0.14664462  0.4594958 ]
 [10.040816    9.382922   -5.25181   ]], shape=(3, 3), dtype=float32)


In [145]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=80,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([46.069298 24.071379 11.163263 47.372303 39.434032], shape=(5,), dtype=float32)


In [148]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.dtypes.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)


# Tensor e Variaveis

In [165]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])
print(tensor_indexed[1:])
print(tensor_indexed[0:-3])
print(tensor_indexed[:2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([ 6  2  4  6 66  7], shape=(6,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


In [154]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [169]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print(tensor_two_d[0:3, 0:2])
print(tensor_two_d[:, 0])
print(tensor_two_d[1:3, 0])
print(tensor_two_d[..., 1])


tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [182]:
tensor_three_d = tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [5,8,0],
        [2,7,0]
    ],
    [
        [2,1,9],
        [4,-3,32]
    ],
])

print(tensor_three_d[0, 1, 2])
print(tensor_three_d[0,:,:])
print(tensor_three_d[0,:,-1])
print(tensor_three_d[0,:,2])
print(tensor_three_d[0:2,:,2])
print(tensor_three_d[0:2, ... ,2])

tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor([ 0 -1], shape=(2,), dtype=int32)
tf.Tensor([ 0 -1], shape=(2,), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)


# Matemática