In [1]:
# Esse código gera imagens a partir de um arquivo pcap
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import sys
import pickle
import pyshark
from PIL import Image, ImageDraw

In [3]:
# Caminho para o arquivo PCAPNG
arquivo = 'pacotes.pcapng'

def criaImagem(pacote):
    # Qual o tipo da variavel pacote?
    print(type(pacote))
    # Converte a string para uma lista de caracteres
    pacote = list(pacote)
    # Cria um vetor com os valores do pacote
    vetor = np.array(pacote)

    # tamanho do arquivo
    tamanho = vetor.size

    print(tamanho)
    
    zeros = list('0'*12)

    # Adiciona zeros para completar o tamanho
    for i in zeros:
        vetor = np.append(vetor, i)


    print(vetor)


    # Cria um vetor com os valores do pacote
    valor_hexadecimal = np.array([])
    for linha in vetor:
        for elemento in linha:
            # Repete o numero 2 vezes e converte para inteiro de 0 a 255
            valor = int(elemento*2, 16)
            # Adiciona o valor ao vetor
            valor_hexadecimal = np.append(valor_hexadecimal, valor)
    
    # Faz o reshape para 10x10
    valor_hexadecimal = valor_hexadecimal.reshape(10,10)

    # Transforma a matriz 10x10 em uma matriz 100x100, mantendo os valores cada valor sendo 10x10
    #valor_hexadecimal = np.kron(valor_hexadecimal, np.ones((10,10)))
    

    print(valor_hexadecimal)

    # Crie uma imagem a partir dos tons de cinza
    imagem = Image.fromarray(valor_hexadecimal, 'L')

    # Salve a imagem em um arquivo (opcional)
    #imagem.save('imagem_em_tons_de_cinza.png')

    # Mostra a imagem (opcional)
    imagem.show()

with pyshark.FileCapture(arquivo, use_json=True,
            include_raw=True) as cap:
    # Pega o primeiro pacote
    pacote = cap[0]

    conteudoEmHexa = pacote.frame_raw.value
    # Pega só os bytes do cabeçalho ip
    conteudoEmHexa = conteudoEmHexa[0:88]

    print(conteudoEmHexa)

    # Cria a imagem
    criaImagem(conteudoEmHexa)





c:\Users\guerr\anaconda3\envs\gan\lib\site-packages\pyshark\capture\capture.py:177: UserWarning: The running eventloop has tasks but pyshark must set a new eventloop to continue. Existing tasks may not run.
  warnings.warn("The running eventloop has tasks but pyshark must set a new eventloop to continue. "


00010001000608000000011100000800450005940001000040115c540a0001010a000404c350c350058001ee
<class 'str'>
88
['0' '0' '0' '1' '0' '0' '0' '1' '0' '0' '0' '6' '0' '8' '0' '0' '0' '0'
 '0' '0' '0' '1' '1' '1' '0' '0' '0' '0' '0' '8' '0' '0' '4' '5' '0' '0'
 '0' '5' '9' '4' '0' '0' '0' '1' '0' '0' '0' '0' '4' '0' '1' '1' '5' 'c'
 '5' '4' '0' 'a' '0' '0' '0' '1' '0' '1' '0' 'a' '0' '0' '0' '4' '0' '4'
 'c' '3' '5' '0' 'c' '3' '5' '0' '0' '5' '8' '0' '0' '1' 'e' 'e' '0' '0'
 '0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
[[  0.   0.   0.  17.   0.   0.   0.  17.   0.   0.]
 [  0. 102.   0. 136.   0.   0.   0.   0.   0.   0.]
 [  0.  17.  17.  17.   0.   0.   0.   0.   0. 136.]
 [  0.   0.  68.  85.   0.   0.   0.  85. 153.  68.]
 [  0.   0.   0.  17.   0.   0.   0.   0.  68.   0.]
 [ 17.  17.  85. 204.  85.  68.   0. 170.   0.   0.]
 [  0.  17.   0.  17.   0. 170.   0.   0.   0.  68.]
 [  0.  68. 204.  51.  85.   0. 204.  51.  85.   0.]
 [  0.  85. 136.   0.   0.  17. 238. 238.   0.   0.]
 [  0.   0