In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

print(array[::-1])

[5 4 3 2 1]


In [6]:
x = np.array([1, 2, 3, 4, 5])
print(x[1:])
print(x[:-1])
print(x[1:]-x[:-1])
print(zip(x[1:],x[:-1]))
# o que é zip?
# https://docs.python.org/3/library/functions.html#zip
[x-y for x,y in zip(x[1:],x[:-1])]

[2 3 4 5]
[1 2 3 4]
[1 1 1 1]


[1, 1, 1, 1]

In [10]:
s = "a1b2c3 werwe r 34234"
print("".join(s.split(" ")))
"".join([c for c in s if c.isalpha()])

a1b2c3werwer34234


'abcwerwer'