In [4]:
import numpy as np

array = np.random.randint(1, 100, size=10)

print(array)

matriz = array.reshape(2, 5)

print(matriz)

[29 97 71 21 43 92 40 72 50 83]
[[29 97 71 21 43]
 [92 40 72 50 83]]
